#!/usr/bin/env bash
# Configuring  Nginx server so that /redirect_me is redirecting to another pag.

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Holberton School" | sudo tee /var/www/html/index.html

# redirection config
replacement="server_name _;\\
    rewrite ^/redirect_me https://github.com/ThierrySHYAKA/ permanent;"
sudo sed -i "s|server_name _;|$replacement|" /etc/nginx/sites-available/default

sudo nginx -t
sudo service nginx start
#setting up nginx server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://onepiece.fandom.com/wiki/One_Piece_Wiki permanent;" /etc/nginx/sites-enabled/default
sudo service nginx restart
